// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtD5DbCWODfQOQwNBCHtBS7V-5_lOiIbw',
    appId: '1:59141031699:web:c830eb1ff45bc9e7befce6',
    messagingSenderId: '59141031699',
    projectId: 'to-do-app-8643d',
    authDomain: 'to-do-app-8643d.firebaseapp.com',
    storageBucket: 'to-do-app-8643d.firebasestorage.app',
    measurementId: 'G-2TNSWR9W3X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCULe-XOxdogucxeJre5t4wQ8RPKA3PBz0',
    appId: '1:59141031699:ios:053f1af3c71aaa6dbefce6',
    messagingSenderId: '59141031699',
    projectId: 'to-do-app-8643d',
    storageBucket: 'to-do-app-8643d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCULe-XOxdogucxeJre5t4wQ8RPKA3PBz0',
    appId: '1:59141031699:ios:053f1af3c71aaa6dbefce6',
    messagingSenderId: '59141031699',
    projectId: 'to-do-app-8643d',
    storageBucket: 'to-do-app-8643d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtD5DbCWODfQOQwNBCHtBS7V-5_lOiIbw',
    appId: '1:59141031699:web:2cecf91389f59190befce6',
    messagingSenderId: '59141031699',
    projectId: 'to-do-app-8643d',
    authDomain: 'to-do-app-8643d.firebaseapp.com',
    storageBucket: 'to-do-app-8643d.firebasestorage.app',
    measurementId: 'G-Q98L6182MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoN4mi0niDSoGzHJl4Y9HPVLXyNjlJJsk',
    appId: '1:59141031699:android:55b9a36f9553d45ebefce6',
    messagingSenderId: '59141031699',
    projectId: 'to-do-app-8643d',
    storageBucket: 'to-do-app-8643d.firebasestorage.app',
  );

}